optimizer: 'adam'  # 'adam' 'sgd'
lr: 0.01
momentum: 0.9  # sgd
scheduler: 'step_lr'
step_size: 10
gamma: 0.1
max_epochs: 3
loss: 'cross_entropy' # or 'binary'
weight_decay: 0.01
batch_size: 34

#softmax, difference binary-cross
#f1 score, prec, rec, prec/recc, mean avg prec - avg prec
#Dropout how works on diff moments
#Max-norm regularization 